version: '3.7'
services:
   bulk-email:
      build: .
      ports:
         - "8080:8080"
      container_name: bulk-email-service
   postgresql:
      image: postgres
      environment:
         - POSTGRES_USER=bulk-email-user
         - POSTGRES_PASSWORD=1234
         - POSTGRES_DB=bulk-email-db
      ports:
         - "127.0.0.1:5433:5432"
      container_name: bulk-email-postgres